title: There's nothing to see below
author: Satishwar Kedas
email: satishwar.kedas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  just a boring old management degree graduate with an interest in data
  jack of multiple trades across health, law, business, computing, statistics

# social links
twitter_username: SatishwarK # DO NOT include the @ character, or else the build will fail!
github_username:  satishwarkedas # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
